apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pam-stillingshistorikk-bigquery
  namespace: teampam
  labels:
    team: teampam
spec:
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 50m
      memory: 1024Mi
  vault:
    enabled: false
  webproxy: false
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  accessPolicy:
    inbound:
      rules:
        - application: pam-ad-api
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  gcp:
    bigQueryDatasets:
      - cascadingDelete: false
        name: stilling_historikk_bq
        permission: READWRITE
  env:
    - name: ADLISTENER_GROUP_ID
      value: stilling_historikk_v2
    - name: ADLISTENER_TOPIC
      value: teampam.stilling-historikk
    - name: ADLISTENER_ENABLED
      value: "true"
    - name: GOOGLE_BIGQUERY_DATASET
      value: stilling_historikk_bq
